### ISSUE TITLE
Switch to https://github.com/karlb/sqlite-sqlean

### ISSUE THREAD

**Issue by cldellow** [cldellow/datasette-ui-extras#69]
I'm going to vendor the linux-x86 crypto.so library as part of #68 

I could also vendor the libs for the other platforms, but I think first I'll wait and see if @karlb's sqlite-sqlean project makes progress - that'd be much easier to manage.

**Comment by cldellow** [comment]
I tried depending on it directly at `git+https://github.com/karlb/sqlite-sqlean`, but PyPI rejected:
https://github.com/cldellow/datasette-ui-extras/actions/runs/4179307326/jobs/7239113347

**Comment by karlb** [comment]
Yes, PyPI does not allow git URLs. You could try sqlite-sqlean==0.1 which I released on PyPI.

Please note that it is not based on the master branch, but on a branch that uses the official sqlean binary release and is thus restricted to the platforms supported by that. See https://github.com/karlb/sqlite-sqlean/issues/1 for more details (feedback welcome!).

Since you are using the crypto extension, I wonder if you have any idea what might be causing https://github.com/karlb/sqlite-sqlean/issues/4?

**Comment by cldellow** [comment]
Oh, wow, thanks, I'll try that, hopefully tonight. I'll leave a note on that issue about the test failures.

**Comment by cldellow** [comment]
The PyPI package works perfectly. Thanks so much for putting in the effort to make that easily used by everyone!
